config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  get '/show', to: 'pages#show'
  
  resources :users, except: [:new]
  
  resources :items
  
  resources :rooms
  
  resources :homes
  
  resources :password_resets
  
  get '/register', to: 'users#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  

end

app/models/home.rb
class Home < ActiveRecord::Base
    belongs_to :user
    has_many :rooms

end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :room
    belongs_to :user
    belongs_to :home
    
    validates :item_name, presence: true, length: {minimum: 3, maximum: 10 }
    validate :purchase_date_cannot_be_in_the_future
    validates :price, presence: true, :numericality => {:greater_than => 0.1, :less_than => 100000}
    mount_uploader :item_picture, PictureUploader
    


  def purchase_date_cannot_be_in_the_future
    errors.add(:purchase_date, "can't be on a future date") if
      !purchase_date.blank? and purchase_date > Date.today
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
    belongs_to :user
    belongs_to :home
    has_many :items
    
    validates :room_name, presence: true 
   
    def item_total
      self.items.size
    end
    
    def item_value
        self.items(:price).sum(:price)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :rooms
    has_many :homes
    has_many :items
    accepts_nested_attributes_for :homes
    
    before_save { self.email = email.downcase }
    #validates :user_name, presence: true, length: { minimum: 3, maximum: 40 } 
    VALIDATE_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: { maximum: 105 }, 
                                      uniqueness: { case_sensitive: false}, 
                                      format: { with: VALIDATE_EMAIL_REGEX }
    has_secure_password
    
    def send_password_reset
        generate_token(:password_reset_token)
        self.password_reset_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver_now
    end
   
   def generate_token(column)
      begin
      self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @home = Home.find(current_user)
  end
    
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   
   
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    respond_to do |format|
      if @item.save
        #do something
        format.json { head :no_content}
        format.js 
        flash[:success] = "Your item was created successfully!"
        #format.html {redirect_to homes_path }
        #redirect_to room_path(@item.room_id)
      else
        format.json { render json: @item.errors.full_messages, 
                            status: :unprocessable_entity }
      end
    
    end
  end
  
  def show
    
  end
   
  def edit
    @item = Item.find(params[:id])
  end
   
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      #do something
      flash[:success] = "Your item was updated successfully!"
      redirect_to room_path(@item.room_id)
    else
    
    render :edit
    
    end
  end
  
  def destroy
    @item = Item.find_by(params[:id])
    @item.destroy
  end
   
   private 
   
    def item_params
      params.require(:item).permit(:item_name,:purchase_date, :price, :home_id, :room_id, :item_picture)
    end
 
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    
    def new
      
    end
    
    def create
    user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:success] = "You are now logged in"
        redirect_to homes_path
      else
      flash.now[:danger] = "Your email address or password doesn't match our records"
      render 'new'
      end
    end
    
    def destroy
      session[:user_id] = nil
      flash[:success] = "You have logged out"
      redirect_to root_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    end

    def show
    
    @user = current_user
    
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    
  def new
  end

  def create
  user = User.find_by_email(params[:email])
    user.send_password_reset if user
    flash[:success] = "Email sent with reset instuctions"
    redirect_to root_url 
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
    
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
      if @user.password_reset_sent_at < 2.hours.ago
        redirect_to new_password_reset_path, flash[:warning] = "Password reset has expired!" 
      elsif @user.update_attributes(params[:user].permit(:password))
        redirect_to root_url 
      else
        render :edit
      end
  end
    
  
   private 
    def user_params
      params.require(:user).permit(:name,:email, :password, homes_attributes: [:home_name])
    end  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  respond_to :js
  
  def new
    @room = Room.new 
  end
  
  def create
    @room = Room.new(room_params)
    @room.user = current_user
      if @room.save
      #flash[:success] = "Task was successfully created." if @room.save
      #respond_with(@room)  
        flash[:success] = "Your item was created successfully!"
        redirect_to room_path(@room)
      else
      render :new  
        #format.js {render file: '/rooms/new.js.erb' } 
        
      end
    #end  
  end

  def show
    @room = Room.find(params[:id])  
  end
  
  def edit
    @room = Room.find(params[:id]) 
  end
 
  def update
     respond_to do |format|
      if @room.update(room_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @room.errors.full_messages,
                                   status: :unprocessable_entity }
      end
     
    end
  end
  
  private 
    def room_params
      params.require(:room).permit(:room_name,:user_id, :home_id)
    end
    
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  before_action :set_user, only: [:edit, :update, :show]
    
  def new
    @user = User.new
    @user.homes.new
    
  end

  def create 
    @user = User.new(user_params)

    if @user.save
      #do something
      session[:user_id] = @user.id
      #@home = Home.create do |u|
        #u.home_name = "New Home"
        #u.user_id = @user.id
      #end
      
      flash[:success] = "Your account has been created successfully!"
      
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end
  
  def show
    #@homes = User.homes(params[:id])  
  end
  
  def index
  end
  
  
  private 
    def user_params
      params.require(:user).permit(:name,:email, :password, homes_attributes: [:home_name])
    end
    
    def set_user 
       @user = User.find(params[:id])
      
    end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
<%= csrf_meta_tags %>

<div class='row'>
  <div class='col-md-12 center'>
    <h1><%= @home.home_name %></h1>
    <hr/>
  </div>
</div>

<!--<div class='row'>
  <div class='col-md-8 col-md-offset-2 center'>
    <div class='btn-group' role='toolbar'>
      <#% @home.rooms.each do |room| %>
      <button type='button' class='btn btn-default'>
        <#%= room.room_name %>
      </button>
      <#% end %>     
    </div>
  </div>
</div>-->
<br>


<!-- <div role="tabpanel">

  <!-- Nav tabs -->
  <div class="tabbable tabs-left">
    <ul class="nav nav-tabs col-md-2" role="tablist">
      <% @home.rooms.each_with_index do |room2, index| %>
      <% if index == 0 %>
      <li role="presentation" class="active"><a href="#<%= index.to_s %>" aria-controls="<%= index.to_s %>" role="tab" data-toggle="tab"><%= room2.room_name %></a></li>
      <% end %>
      <% if index >= 1 %>
      <li role="presentation"><a href="#<%= index.to_s %>" aria-controls="<%= index.to_s %>" role="tab" data-toggle="tab"><%= room2.room_name %></a></li>
      <!--<li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
      <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>-->
      <% end %>
      <% end %>
     <li role="presentation"><a href="#add" aria-controls="add" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-plus"></span></a></li>
    </ul>
  </div>
  <!-- Tab panes -->
 
  <div class="tab-content">
    <% @home.rooms.each_with_index do |room3, index| %> 
    <% if index == 0 %>
    <div role="tabpanel" class="tab-pane fade in active" id="<%= index.to_s %>">
      <div class='col-md-8 col-md-offset-1  center'>
        <!--<h3><#%= room3.room_name %></h3>-->
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <% room3.items.each_with_index do |item, index| %>
      <div class="panel panel-default">
        <div class="panel-heading center" role="tab" id="heading<%room3.room_name %><%= index.to_s %>" data-toggle="collapse" data-parent="#accordion" href="#collapse<%room3.room_name %><%= index.to_s %>" aria-expanded="false" aria-controls="collapse<%room3.room_name %><%= index.to_s %>">
          <h3 class="panel-title">
            <p>
              <%= item.item_name %>
            </p>
          </h3>
        </div>
        <div id="collapse<%room3.room_name %><%= index.to_s %>" class="panel-collapse collapse " role="tabpanel" aria-labelledby="heading<%room3.room_name %><%= index.to_s %>">
          <div class="panel-body">
            <img src=<%= item.item_picture %> width='75' height='75' class='pull-left'>
          </div>
        </div>
      </div>
      <% end %>
      </div>
      </div>
    </div>
    <% end %>
    <% if index >= 1 %>
    <div role="tabpanel" class="tab-pane fade" id="<%= index.to_s %>">
      <div class='col-md-8 col-md-offset-1 center'>
        <!--<h3><#%= room3.room_name %></h3>-->
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <% room3.items.each_with_index do |item, index| %>
          <div class="panel panel-default">
            <div class="panel-heading center" role="tab" id="heading<%=room3.room_name %><%= index.to_s %>" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=room3.room_name %><%= index.to_s %>" aria-expanded="false" aria-controls="collapse<%=room3.room_name %><%= index.to_s %>">
              <h3 class="panel-title">
                <p>
                  <%= item.item_name %>
                </p>
              </h3>
            </div>
            <div id="collapse<%=room3.room_name %><%= index.to_s %>" class="panel-collapse collapse " role="tabpanel" aria-labelledby="heading<%=room3.room_name %><%= index.to_s %>">
            <div class="panel-body">
              test
            </div>
            </div>
          </div>
        <% end %>
        </div>
      
      </div>
      
    </div>
    <div role="tabpanel" class="tab-pane fade" id="add">
    </div>
    <% end %>
    <% end %>
    <div class='col-md-8 col-md-offset-1 center'>
      <%= link_to "New Item", new_item_path, remote: true, class: "btn btn-default wide" %><!--<button type='button' class='btn btn-default wide'><span class='glyphicon glyphicon-plus'></span></button>-->
    </div>
  </div>

<!--<#%= link_to(new_room_path, remote: true, class: 'btn btn-primary btn-edit') do %><span class="glyphicon glyphicon-plus"></span><#% end %>-->

<%= render 'rooms/dialog' %>

<script type="text/javascript">
$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
</script>

app/views/items/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog"
           aria-labelledby="myModalLabel"
           aria-hidden="true"
           data-backdrop="static"
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
    
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/items/_form.html.erb
<!--<#%= form_for(@item, remote: true, :html => { :role => "form" }) do |f| %>-->


<%= form_for(@item, remote: true,  :html => { :role => "form" }) do |f| %>
<div id="error_explanation" class="bg-danger text-danger">
</div>        
      <%= f.label :item_name %>
      <%= f.text_field :item_name, :placeholder => "placeholder text" %>
      <span class="picture">
        <%= f.file_field :item_picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.label :purchase_date %>
      <%= f.date_field :purchase_date, class: "form-control" %>
      
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control", step: "0.01" %>
      <%= f.label :Home %>
      <%= f.select :home_id, current_user.homes.collect{ |c| [c.home_name, c.id] } %>
      <%= f.label :Room %>
      <%= f.select :room_id, current_user.rooms.collect{ |c| [c.room_name, c.id] } %>
      
      
      <div class="modal-footer">
        <%= f.submit class:"btn btn-success" %>
      </div> 
        
      <% end %>
      
<!--html: {multipart: true},-->

app/views/items/create.js.erb
$('#dialog').modal('toggle');

app/views/items/edit.html.erb
<%= render 'shared/errors', obj: @item %>

<div class="col-lg-12 center">
  <h1>Update Item</h1>
  <hr/>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 center">
    <div class="well">
      <%= form_for @item do |f| %>
        
      <%= f.label :item_name %>
      <%= f.text_field :item_name, :placeholder => "placeholder text" %>
      
      <%= f.label :purchase_date %>
      <%= f.date_field :purchase_date %>
      
      <%= f.label :price %>
      <%= f.number_field :price %>
      <%= f.label :Home %>
      <%= f.select :home_id, current_user.homes.collect{ |c| [c.home_name, c.id] } %>
      <%= f.label :Room %>
      <%= f.select :room_id, current_user.rooms.collect{ |c| [c.room_name, c.id] } %>
      
      
      <%= f.submit class:"btn btn-success" %>
        
      <% end %>
    </div>
  </div>  
</div>

app/views/items/new.html.erb
<%= render 'shared/errors', obj: @item %>

<div class="col-lg-12 center">
  <h1>Create New Item</h1>
  <hr/>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 center">
    <div class="well">
      <%= form_for @item do |f| %>
        
      <%= f.label :item_name %>
      <%= f.text_field :item_name, :placeholder => "placeholder text" %>
      
      <%= f.label :purchase_date %>
      <%= f.date_field :purchase_date, class: "form-control" %>
      
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control", step: "0.01" %>
      <%= f.label :Home %>
      <%= f.select :home_id, current_user.homes.collect{ |c| [c.home_name, c.id] } %>
      <%= f.label :Room %>
      <%= f.select :room_id, current_user.rooms.collect{ |c| [c.room_name, c.id] } %>
      
      
      <%= f.submit class:"btn btn-success" %>
        
      <% end %>
    </div>
  </div>  
</div>

app/views/items/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Create New Item");
 
// Render the new form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus()
  })

app/views/items/notnew.html.erb
<%= render 'shared/errors', obj: @item %>

<div class="col-lg-12 center">
  <h1>Create New Item</h1>
  <hr/>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3 center">
    <div class="well">
      <%= form_for @item do |f| %>
        
      <%= f.label :item_name %>
      <%= f.text_field :item_name, :placeholder => "placeholder text" %>
      
      <%= f.label :purchase_date %>
      <%= f.date_field :purchase_date, class: "form-control" %>
      
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control", step: "0.01" %>
      <%= f.label :Home %>
      <%= f.select :home_id, current_user.homes.collect{ |c| [c.home_name, c.id] } %>
      <%= f.label :Room %>
      <%= f.select :room_id, current_user.rooms.collect{ |c| [c.room_name, c.id] } %>
      
      
      <%= f.submit class:"btn btn-success" %>
        
      <% end %>
    </div>
  </div>  
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div id="alert-item" class="col-md-12">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %>
            </div>
        <% end %>
    </div>
</div>
<script type="text/javascript">
$("#alert-item").fadeTo(2500, 500).slideUp(500, function(){
    $("#alert-item").alert('close');
});
</script>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "Insurable", '', class: "btn-lg", id: "logo"%>
      <% if logged_in? %>
        <div class="nav_user_icon">
          <div class="dropdown">
            <%= link_to '#', class: "btn btn-default dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.name %> <b class="caret"></b>
            <% end %>
            <ul class='dropdown-menu'>
                <li><%= link_to "Home Summary", user_path(current_user) %></li>
                <li><%= link_to "Room Summary", homes_path %></li>
                <li><%= link_to "Edit Profile", '' %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", logout_path %></li>
              </ul>
            </div>
          </div>
        <% else %>
        <form id="signin" class="navbar-form navbar-right" role="form">
            <div class="input-group">
              <%= form_for :logins, :url=>{ :controller => :logins, :action => :new}, :remote => true do |f| %>
              <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <%= f.email_field :email, :class => 'form-control', :placeholder => "Email Address" %>        
                            <!--<input id="email" type="email" class="form-control" name="email" value="" placeholder="Email Address">                                        
                        --></div>
                      
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <%= f.password_field :password, :class => 'form-control', :placeholder => "Password" %>
                            <!--<input id="password" type="password" class="form-control" name="password" value="" placeholder="Password">                                        
                        --></div>
                    <%= f.submit 'Login', class: 'btn btn-primary' %>
                        <!--<button type="submit" class="btn btn-primary">Login</button>-->
                   </form>   
              <% end %>
        </div>
        <div class="nav_user_icon">
          <%= link_to "login", login_path, class: "btn btn-primary", id:"login-active" %>
        </div>
        <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insurable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= render "layouts/navigation" %>

<div class="container">

  <%= render 'layouts/messages' %>

  <%= yield %>

  
  
  <!--<div class='footer col-md-12'>
    <div class='pull-right'>
      <p>&copy; Twiggystudios</p>
    </div>
  </div>-->
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class='row'>
  <br>
  <% if !logged_in? %>
    <div class='jumbotron'>
      <h1 class="center">Welcome to Insurable!</h1>
      <p class="center">Making cataloging your personal items simple and fun!</p>
      <div class="center">
        <%= link_to "Signup Now!", register_path, data: { modal: true }, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% else %>
  <div class="col-lg-12 center">
    <h1>Hello</h1>
    <hr/>
  </div>
  
  <div class='row'>
    <div class='col-md-3'>
      <div class='well'>
        <h2>This is where Homes and Rooms will be displayed</h2>
      </div>
    </div>
    <div class='col-md-9'>
      <div class='well'>
        <h2>This is where Items will be displayed</h2>
      </div>
    </div>
  </div>
  
  <div class="wrapper">
  <div class="content-main">...</div>
  <div class="content-secondary">...</div>
</div>
  <% end %>
</div>

<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
  </div>
</div>

app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>

    
   
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <!--<div class="field">
    <#%= f.label :password_confirmation %>
    <#%= f.password_field :password_confirmation %>
  </div>-->
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
    <div id="error_explanation" class="bg-danger text-danger">
</div>        
    <%= f.label :Home %>
    <%= f.select :home_id, current_user.homes.collect{ |c| [c.home_name, c.id] } %>
            
    <%= f.label :room_name %>
    <%= f.text_field :room_name %>
    <div class="modal-footer">
    <%= f.submit class:"btn btn-success" %>
    </div> 
<% end %>

app/views/rooms/show.html.erb
<div class='row'>
    <h1 class='col-md-4 col-md-offset-4 center'><%= @room.room_name %></h1>
    
  </div>
</div>
<div class='row'>
    <div class='col-md-4 col-md-offset-4 center'>
        <%= link_to 'Add Item', new_item_path, remote: true, class: 'btn btn-primary' %>
        <%= link_to 'Add Room', new_room_path, remote: true, class: 'btn btn-primary' %>
    </div>
</div>
<hr/>
<!--<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
        <table class='table table condensed'>
          <thead>
            <tr>
              <th>Image</th>
              <th>Item Name</th>
              <th>Purchase Date</th>
              <th>Value</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <#% @room.items.each do |item_test| %>
              <th><a href="#" class="thumbnail"><img src="https://placehold.it/140x140" alt=""></a></th>
              <th><#%= item_test.item_name %></th>
              <th><#%= item_test.purchase_date %></th>
              <th><#%= item_test.price %></th>
              <th><#%= link_to 'Edit',edit_item_path(item_test), class:'btn btn-primary btn-sm' %>  <#%= link_to 'Delete', '', class:'btn btn-danger btn-sm' %></th>
            </tr>
            <#% end %>
          </tbody>
            
        </table>
        
    </div>
</div>
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
        <#% @room.items.each do |item| %>
        <div class='panel panel-info'>
            <div class='panel-heading'>
            <h4 class='panel-title center'><#%= item.item_name %> </h4> 
            </div>
            <div class='panel-body'>
                <div class='row'>
                    <div class="col-md-2 col-md-offset-1">
                        <a href="#" class="thumbnail">
                        <#%= image_tag(item.item_picture.url) %>
                        </a>
                    </div>
                    <div class='col-md-2 top-offset'>
                        <h4 class='center'>Bought on:<#%= item.purchase_date %>  </h5>
                    </div>
                    <div class='col-md-2 top-offset'>
                        <h4 class='center'>Value: $<#%= item.price %>.00</h5>
                    </div>
                    <div class='col-md-3 top-offset'>
                        <h4><#%= link_to 'Edit',edit_item_path(item), class:'btn btn-primary' %> / <#%= link_to 'Delete','', class:'label label-danger' %></h4>
                    </div>
                </div>
            </div>
        </div>
        <#% end %>
    </div>
</div>
-->
<div class='row'>
<div class="col-md-8 col-md-offset-2">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <% @room.items.each_with_index do |item, index| %>
      <div class="panel panel-default">
        <div class="panel-heading center" role="tab" id="heading<%= index.to_s %>" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index.to_s %>" aria-expanded="false" aria-controls="collapse<%= index.to_s %>">
          <h3 class="panel-title">
            <p>
              <%= item.item_name %>
            </p>
          </h3>
        </div>
        <div id="collapse<%= index.to_s %>" class="panel-collapse collapse " role="tabpanel" aria-labelledby="heading<%= index.to_s %>">
          <div class="panel-body">
            test
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>  
    
<!--<div class="btn btn-primary btn-edit"><span class="glyphicon glyphicon-plus"></span></div>-->

 <%= link_to(new_room_path, remote: true, class: 'btn btn-primary btn-edit') do %><span class="glyphicon glyphicon-plus"></span><% end %>

<%= render 'dialog' %>

app/views/users/show.html.erb
<% @user.homes.each do |home| %>
<%= link_to "Add Room", new_room_path, class: 'btn btn-primary'%>
<%= link_to "Add Item", new_item_path, class: 'btn btn-primary'%>
<br>
<br>
<div class='row'>
  <div class='col-md-2'>
    <ul class="nav nav-pills nav-stacked">
      <li role="presentation" class="active"><%= link_to "Summary", user_path(current_user) %></li>
      <li role="presentation"><a href="#">Rooms</a></li>
      <li role="presentation"><a href="#">Messages</a></li>
    </ul>
  </div>
    <div class="col-md-10 center">
      <h2><%= home.home_name %></h2>
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Room</th>
          <th class="center"># Of Items</th>
          <th class="center">Total Value</th>
        </tr>
        </thead>
        <tbody>
        <% @user.rooms.each do |room| %>
        <tr>
          <td><%= link_to room.room_name, room_path(room) %></td>
          <td class="center"><%= room.item_total %></td>
          <td class="center">$<%= room.item_value %>.00</td>
        </tr>
        <% end %>
        </tbody>
      </table>
  </div>
<% end %>